"""Modelo ``Source`` — veículo de notícia (ex.: Valor Econômico)."""

from typing import TYPE_CHECKING

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from news_sentiment.infrastructure.db.base import Base
from news_sentiment.infrastructure.db.mixins import TimestampMixin

if TYPE_CHECKING:
    from news_sentiment.infrastructure.db.models.article import Article


class Source(Base, TimestampMixin):
    """Catálogo de fontes de notícia consumidas pelo scraper.

    Ordem de herança: ``Base`` primeiro (traz a ``metadata``),
    ``TimestampMixin`` depois (injeta ``created_at`` / ``updated_at``).
    """

    # Nome da tabela no banco. Convenção do projeto: ``snake_case`` no
    # plural ("sources", "articles"). O SQLAlchemy não normaliza isso
    # automaticamente — é escolha sua.
    __tablename__ = "sources"

    # ── Colunas ──────────────────────────────────────────────────────

    # PK Integer (decisão 3). Quando você define ``primary_key=True``
    # numa coluna ``int`` sem ``autoincrement=False``, o Postgres gera
    # uma sequência automática (``GENERATED BY DEFAULT AS IDENTITY``).
    # Não precisa declarar autoincrement explicitamente.
    id: Mapped[int] = mapped_column(primary_key=True)

    # Nome display, ex.: "Valor Econômico".
    # ``String(200)`` vira ``VARCHAR(200)`` no Postgres. Limitar tamanho
    # é proteção contra payload absurdo — não é restrição de negócio.
    name: Mapped[str] = mapped_column(String(200), nullable=False)

    # Slug = identificador estável usado em código e configs (ex.:
    # ``"valor_economico"``). Diferente do ``name``, não muda com
    # rebrand do veículo.
    #
    # ``unique=True`` cria índice único — duas linhas não podem ter o
    # mesmo slug, garantia no nível de banco (não confie só na app).
    slug: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)

    # URL da home do veículo, ex.: ``"https://valor.globo.com"``.
    base_url: Mapped[str] = mapped_column(String(500), nullable=False)

    # Toggle para desabilitar uma fonte sem deletar a linha (preserva
    # FKs em ``Article``). ``default=True`` é app-side: o ORM injeta
    # ``True`` se você não passar nada. Para garantia no banco também
    # (ex.: ``INSERT`` via psql), usar ``server_default=text("true")``.
    # Vamos manter app-side por simplicidade — a migration manual pode
    # adicionar ``server_default`` se necessário.
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)

    articles: Mapped[list["Article"]] = relationship("Article", back_populates="source")
    # Observações pedagógicas (não vai pro código final):
    #
    # 1) Falta ``__repr__``? Útil pra debug, mas opcional. SQLAlchemy
    #    já gera um decente.
    #
    # 2) Falta ``relationship("Article", back_populates="source")``?
    #    Sim — adicionar quando ``Article`` existir. Sem isso, você
    #    ainda consegue navegar via query manual; o ``relationship``
    #    é açúcar pra ``source.articles`` virar lista carregada.
